apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: tomcatserver
  name: tomcatserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tomcatserver
    spec:
      containers:
      - image: gajjelli/kuberneteswithtomcatmongodb:latest
        name: tomcat
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
